#%RAML 1.0 Trait
  usage: Apply this trait to unforce client_id identification
  headers:
    client_id:
      type: string
      description: Client secret to autheticate system API
      required: true
    client_secret:
      type: string
      required: true
      description: Client secret to autheticate system API